import pandas as pd
import numpy as np
from hmmlearn.hmm import GaussianHMM
from sklearn.preprocessing import StandardScaler
import os
import sys

def prepare_hmm_features(df):
    """
    HMMs require strictly stationary features.
    No raw prices, no raw moving averages.
    """
    df = df.copy()
    
    # 1. Log Returns (Velocity & Direction)
    df['log_return'] = np.log(df['close'] / df['close'].shift(1))
    
    # 2. Normalized Volatility (Is the 4H bar expanding?)
    df['atr_20'] = (df['high'] - df['low']).rolling(20).mean()
    df['norm_range'] = (df['high'] - df['low']) / (df['atr_20'] + 1e-9)
    
    # 3. Bar Structure (ICT Bridge: 1 = closed at high, 0 = closed at low)
    df['close_location'] = (df['close'] - df['low']) / (df['high'] - df['low'] + 1e-9)
    
    # Drop NaNs created by rolling and shift
    return df.dropna()

def walk_forward_hmm(csv_path, window_size=500, n_regimes=4):
    """
    Simulates real-time execution. No lookahead bias.
    Trains a new model for every single bar based only on the past.
    """
    # --- Data Loading and H4 Extraction ---
    # --- ADDED: File existence check for better error handling ---
    if not os.path.exists(csv_path):
        print(f"--- FATAL ERROR ---")
        print(f"Input file not found at the specified path: '{os.path.abspath(csv_path)}'")
        print("\nThis script requires the multi-timeframe data file generated by 'Fetch_Data.py'.")
        print("Please run 'python Fetch_Data.py' first to create the necessary input file.")
        sys.exit(1) # Exit the script with an error code

    try:
        df_raw = pd.read_csv(csv_path, index_col=0, parse_dates=True)
    except (ValueError, KeyError):  # Fallback for files without a datetime index
        df_raw = pd.read_csv(csv_path)

    if any('_H4' in c for c in df_raw.columns):
        print("Detected multi-timeframe data. Extracting H4 data for HMM analysis...")
        h4_cols = [c for c in df_raw.columns if '_H4' in c or '_4H' in c]
        open_c = next((c for c in h4_cols if 'Open' in c or 'open' in c), None)
        high_c = next((c for c in h4_cols if 'High' in c or 'high' in c), None)
        low_c = next((c for c in h4_cols if 'Low' in c or 'low' in c), None)
        close_c = next((c for c in h4_cols if 'Close' in c or 'close' in c), None)

        if all([open_c, high_c, low_c, close_c]):
            df_raw = df_raw[[open_c, high_c, low_c, close_c]].copy()
            df_raw.columns = ['open', 'high', 'low', 'close']
            df_raw = df_raw.dropna().drop_duplicates().reset_index()
        else:
            print("Warning: H4 columns detected, but could not find all OHLC columns. Falling back to base columns.")
            df_raw.columns = [c.lower() for c in df_raw.columns]
            if not any(col in ['date', 'datetime', 'time'] for col in df_raw.columns):
                df_raw.reset_index(inplace=True)
    else:
        df_raw.columns = [c.lower() for c in df_raw.columns]
        if not any(col in ['date', 'datetime', 'time'] for col in df_raw.columns):
            df_raw.reset_index(inplace=True)

    col_map = {c: 'time' for c in df_raw.columns if c.lower() in ['date', 'datetime', df_raw.columns[0]]}
    df_raw.rename(columns=col_map, inplace=True)
    if 'time' in df_raw.columns:
        df_raw['time'] = pd.to_datetime(df_raw['time'])
        df_raw = df_raw.sort_values('time').reset_index(drop=True)
    # --- End Data Loading ---

    df = prepare_hmm_features(df_raw)

    results = []
    total_bars = len(df)
    prev_confidence = 1.0 # Track the previous bar's confidence
    
    print(f"Starting Walk-Forward... Window Size: {window_size} | Total Bars: {total_bars}")

    # Process each bar as if it were 'Today'
    for i in range(window_size, total_bars):
        # 1. Slice 'Past Data' (The Only Data Available)
        window = df.iloc[i-window_size:i+1].copy()
        
        # 2. Local Scaling (Kills the Scaling Leak)
        features = ['log_return', 'norm_range', 'close_location']
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(window[features].values)
        
        # 3. Local Training
        model = GaussianHMM(n_components=n_regimes, covariance_type="full", n_iter=100, random_state=42)
        try:
            model.fit(X_scaled)
        except ValueError as e:
            print(f"Skipping bar {i} due to HMM fit error: {e}")
            continue
        
        # 4. Local Prediction (Today's State Only)
        current_state = model.predict(X_scaled)[-1]
        probs = model.predict_proba(X_scaled)[-1]
        confidence = np.max(probs)
        
        # 5. Dynamic Mapping (Ensures IDs are consistent across windows)
        means = model.means_
        retrace_idx = np.argmin(means[:, 0]) # Lowest return
        breakout_idx = np.argmax(means[:, 0]) # Highest return
        others = [idx for idx in range(n_regimes) if idx not in [retrace_idx, breakout_idx]]
        
        if means[others[0], 0] > means[others[1], 0]:
            grind_idx, cons_idx = others[0], others[1]
        else:
            grind_idx, cons_idx = others[1], others[0]
            
        mapping = {retrace_idx: 'Retracement', breakout_idx: 'ATH_Breakout', 
                   cons_idx: 'Consolidation', grind_idx: 'ATH_Grind'}
        
        base_regime = mapping[current_state]
        
        # =========================================================
        # INSTITUTIONAL CIRCUIT BREAKERS (BYPASSING THE 8-HOUR LAG)
        # =========================================================
        
        current_norm_range = window['norm_range'].iloc[-1]
        current_log_return = window['log_return'].iloc[-1]
        
        final_regime = base_regime # Default
        
        # 1. VOLATILITY SHOCK OVERRIDE (Zero Lag)
        # If the 4H candle is > 2.5x the average ATR, we ignore the HMM entirely.
        if current_norm_range > 2.5:
            if current_log_return > 0:
                final_regime = 'ATH_Breakout'
            else:
                final_regime = 'Retracement'
            confidence = 1.0 # Force maximum confidence
            
        # 2. PROBABILITY DECAY (Early Warning System)
        # If confidence drops by more than 25% in a single bar, the regime is fracturing.
        elif (prev_confidence - confidence) > 0.25:
            final_regime = 'Uncertain'
            
        # 3. HIGH UNCERTAINTY THRESHOLD (Raised from 60% to 75%)
        elif confidence < 0.75:
            final_regime = 'Uncertain'
            
        else:
            final_regime = base_regime
            
        # Update prev_confidence for the next loop iteration
        prev_confidence = confidence

        # =========================================================

        # 6. Capture the 'Live' result
        results.append({
            'time': window['time'].iloc[-1],
            'close': window['close'].iloc[-1],
            'log_return': current_log_return,
            'norm_range': current_norm_range,
            'Raw_HMM_Regime': base_regime,
            'Stable_Regime': final_regime,
            'regime_confidence': confidence
        })
        
        if (i - window_size) % 50 == 0:
            print(f"Bar {i} processed. Current Regime: {final_regime}")

    wf_df = pd.DataFrame(results)

    # ==========================================
    # STAGE D: ENSEMBLE, HYSTERESIS & CUSUM BIAS
    # ==========================================
    
    # 4. HYSTERESIS (Dynamic Numeric Smoothing)
    # ==========================================
    # Step A: Dynamically extract whatever regimes currently exist in the dataframe.
    # This prevents hardcoding in the mapping step.
    unique_regimes = wf_df['Stable_Regime'].dropna().unique()
    regime_to_id = {name: idx for idx, name in enumerate(unique_regimes)}
    id_to_regime = {idx: name for name, idx in regime_to_id.items()}

    # Step B: Convert strings to numeric IDs for pandas rolling math.
    wf_df['Stable_Regime_Id'] = wf_df['Stable_Regime'].map(regime_to_id)

    # Step C: Apply the 3-bar rolling mode to the numeric IDs.
    wf_df['Stable_Regime_Id'] = wf_df['Stable_Regime_Id'].rolling(window=3).apply(
        lambda x: pd.Series(x).mode().iloc[0],
        raw=False
    ).fillna(method='bfill').astype(int)

    # Step D: Map the smoothed numeric IDs back to their string names.
    wf_df['Stable_Regime'] = wf_df['Stable_Regime_Id'].map(id_to_regime)

    # Optional: keep the ID column, or drop for clean output.
    wf_df.drop(columns=['Stable_Regime_Id'], inplace=True)

    # 5. CUSUM Bias
    # We calculate the cumulative sum of log returns over a 20-bar window.
    wf_df['cusum_20'] = wf_df['log_return'].rolling(window=20).sum().bfill()
    wf_df['ICT_Bias'] = np.where(wf_df['cusum_20'] > 0, 'BULLISH', 'BEARISH')

    print("\n--- STAGE D: ENSEMBLE APPLIED ---")
    print("Added Stable_Regime (Smoothed), ICT_Bias, and Circuit Breakers.")
    
    return wf_df


# --- EXECUTION ---
# Make sure you pip install hmmlearn first
if __name__ == "__main__":
    import sys
    # The input should be the raw multi-timeframe data
    input_file = 'XAUUSD_2023_2025_Data.csv'
    output_file = 'HMM_Walk_Forward_Regime.csv'
    
    if len(sys.argv) > 1:
        input_file = sys.argv[1]
    if len(sys.argv) > 2:
        output_file = sys.argv[2]

    final_df = walk_forward_hmm(input_file)
    if final_df is not None:
        final_df.to_csv(output_file, index=False)
        print(f"\nWalk-forward analysis complete. Results saved to {output_file}")